<?php

namespace App\Services\Workflows;

use Illuminate\Support\Arr;
use Illuminate\Support\Str;

class WorkflowTaskCatalog
{
    public function all(): array
    {
        return [
            'browser.open' => [
                'label' => 'Browserfenster oeffnen',
                'kind' => 'browser',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/browser/open.cjs',
                'timeout_seconds' => 60,
                'description' => 'Startet oder uebernimmt einen Browser-Kontext fuer weitere Workflow-Karten.',
                'form' => [
                    'selector' => false,
                    'value' => false,
                    'url' => false,
                    'success_payload' => false,
                    'failure_payload' => false,
                ],
            ],
            'browser.open_url' => [
                'label' => 'URL aufrufen',
                'kind' => 'browser',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/browser/open_url.cjs',
                'timeout_seconds' => 120,
                'description' => 'Navigiert zu einer variablen URL und wartet optional auf ein Ziel-Element.',
                'form' => [
                    'selector' => false,
                    'value' => false,
                    'url' => true,
                    'url_label' => 'URL',
                    'url_placeholder' => 'https://example.test oder person.webmailUrl',
                    'success_payload' => false,
                    'failure_payload' => true,
                ],
            ],
            'browser.open_webmail_session' => [
                'label' => 'Browser-Session laden und Webmailportal oeffnen',
                'kind' => 'browser',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/browser/open_webmail_session.cjs',
                'timeout_seconds' => 120,
                'description' => 'Laedt gespeicherte Webmail-Cookies und Browser-Storage der Bezugs-Person oder des Haupt-Verifikationskontos und oeffnet das Webmailportal.',
                'form' => [
                    'selector' => false,
                    'value' => false,
                    'url' => false,
                    'mailbox_source' => true,
                    'mailbox_source_label' => 'Script-Bezugsperson',
                    'mailbox_source_options' => [
                        'person' => 'Bezugs-Person',
                        'verification' => 'Haupt-Verifikationskonto',
                    ],
                    'success_payload' => true,
                    'failure_payload' => true,
                ],
            ],
            'webmail.check_session' => [
                'label' => 'Webmailportal-Session pruefen',
                'kind' => 'browser',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/webmail/check_session.cjs',
                'timeout_seconds' => 120,
                'description' => 'Prueft, ob eine gespeicherte oder aktuell offene Webmail-Session verwendbar ist.',
                'form' => [
                    'selector' => false,
                    'value' => false,
                    'url' => false,
                    'mailbox_source' => true,
                    'mailbox_source_label' => 'Script-Bezugsperson',
                    'mailbox_source_options' => [
                        'person' => 'Bezugs-Person',
                        'verification' => 'Haupt-Verifikationskonto',
                    ],
                    'success_payload' => true,
                    'failure_payload' => true,
                ],
            ],
            'webmail.read_verification_code' => [
                'label' => 'Verifizierungscode aus Webmail lesen',
                'kind' => 'browser',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/webmail/read_verification_code.cjs',
                'timeout_seconds' => 90,
                'description' => 'Oeffnet aktuelle Webmail-Nachrichten, sucht in den letzten Mails nach einem Verifizierungscode und merkt ihn als Workflow-Variable.',
                'form' => [
                    'selector' => false,
                    'value' => true,
                    'value_required' => false,
                    'value_label' => 'Optionaler Suchtext',
                    'value_placeholder' => 'Instagram, Sicherheitscode, Domain oder leer',
                    'url' => false,
                    'success_payload' => true,
                    'failure_payload' => true,
                ],
            ],
            'mail.inbox_list_scan' => [
                'label' => 'Mail-Inbox-Liste scannen',
                'kind' => 'browser',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/mail/inbox_list_scan.cjs',
                'timeout_seconds' => 60,
                'description' => 'Liest eine Webmail-Inbox-Liste ueber einstellbare Listen- und Listitem-Selectoren aus und speichert die Treffer als Workflow-Array.',
                'form' => [
                    'selector' => true,
                    'selector_required' => false,
                    'selector_label' => 'Listen-Selector',
                    'selector_placeholder' => '[role=list], [class*=inbox] oder leer fuer Fallbacks',
                    'value' => true,
                    'value_required' => false,
                    'value_label' => 'Listitem-Selector',
                    'value_placeholder' => '[role=row], li, tr oder leer fuer Fallbacks',
                    'url' => false,
                    'success_payload' => false,
                    'failure_payload' => false,
                    'extra_fields' => [
                        [
                            'name' => 'output_array_name',
                            'label' => 'Ausgabe-Array',
                            'placeholder' => 'inbox_mails',
                            'default' => 'inbox_mails',
                            'tab' => 'Ausgabe',
                        ],
                        [
                            'name' => 'subject_selector',
                            'label' => 'Betreff-Selector',
                            'placeholder' => '[class*=subject]',
                            'tab' => 'Filter',
                        ],
                        [
                            'name' => 'title_selector',
                            'label' => 'Titel-Selector',
                            'placeholder' => '[title], [class*=title]',
                            'tab' => 'Filter',
                        ],
                        [
                            'name' => 'subject_filter',
                            'label' => 'Betreff muss enthalten',
                            'placeholder' => "['queued', 'running', 'waiting'] oder queued",
                            'help' => 'Mehrere Werte als Array-Schreibweise, durch Komma oder je Zeile. Mindestens ein Wert muss im Betreff vorkommen.',
                            'span' => 'full',
                            'tab' => 'Filter',
                        ],
                        [
                            'name' => 'title_filter',
                            'label' => 'Titel muss enthalten',
                            'placeholder' => "['queued', 'running', 'waiting'] oder queued",
                            'help' => 'Optional. Wenn Betreff- oder Titelfilter passt, wird die Mail uebernommen.',
                            'span' => 'full',
                            'tab' => 'Filter',
                        ],
                        [
                            'name' => 'mail_ids',
                            'label' => 'Mail-IDs',
                            'placeholder' => "['message-123', 'message-456']",
                            'help' => 'Optional. Uebernimmt nur Listeneintraege, deren data-message-id, data-mail-id, data-id, id oder href passt.',
                            'span' => 'full',
                            'tab' => 'Filter',
                        ],
                        [
                            'name' => 'search_input_selector',
                            'label' => 'Webmail-Suchfeld Selector',
                            'placeholder' => 'input[type=search], input[aria-label*=Suche]',
                            'help' => 'Optional. Wenn Suchfeld und Suchwert gesetzt sind, wird zuerst die Webmail-Suche ausgefuehrt. Betreff- und Titelfilter werden danach ignoriert.',
                            'span' => 'full',
                            'tab' => 'Webmail-Suche',
                        ],
                        [
                            'name' => 'search_value',
                            'label' => 'Webmail-Suchwert',
                            'placeholder' => 'Proton, Instagram oder security@mail.instagram.com',
                            'help' => 'Fester Suchtext oder Name/Pfad einer Workflow-Variable.',
                            'span' => 'full',
                            'tab' => 'Webmail-Suche',
                        ],
                        [
                            'name' => 'search_button_selector',
                            'label' => 'Suchen-Button Selector',
                            'placeholder' => 'button[type=submit], button:has-text("Suchen")',
                            'help' => 'Optional. Wenn leer, wird nach dem Fuellen des Suchfelds Enter gedrueckt.',
                            'span' => 'full',
                            'tab' => 'Webmail-Suche',
                        ],
                        [
                            'name' => 'search_wait_ms',
                            'label' => 'Warten nach Suche (ms)',
                            'type' => 'number',
                            'min' => 0,
                            'max' => 30000,
                            'step' => 100,
                            'placeholder' => '1200',
                            'default' => '1200',
                            'tab' => 'Webmail-Suche',
                        ],
                        [
                            'name' => 'date_selector',
                            'label' => 'Datum-Selector',
                            'placeholder' => 'time, [title], [class*=date]',
                            'tab' => 'Zeit',
                        ],
                        [
                            'name' => 'date_attribute',
                            'label' => 'Datum-Attribut',
                            'placeholder' => "title oder ['datetime', 'title']",
                            'help' => 'Attribut am Datumselement, z.B. title, datetime, data-date. Leer nutzt Text und Standardattribute.',
                            'tab' => 'Zeit',
                        ],
                        [
                            'name' => 'max_age_minutes',
                            'label' => 'Mail maximal alt (Minuten)',
                            'type' => 'number',
                            'min' => 0,
                            'max' => 10080,
                            'step' => 1,
                            'placeholder' => '15',
                            'tab' => 'Zeit',
                        ],
                        [
                            'name' => 'mail_time_gmt_offset_hours',
                            'label' => 'GMT-Offset der Mailzeit',
                            'type' => 'number',
                            'min' => -14,
                            'max' => 14,
                            'step' => 0.5,
                            'placeholder' => '0',
                            'default' => '0',
                            'help' => 'Zeitzone der im Mail-Listeneintrag erkannten Uhrzeit. Beispiel: 0 fuer GMT/UTC. Die Ausgabe wird automatisch in die Zeitzone des Browserfensters umgerechnet.',
                            'tab' => 'Zeit',
                        ],
                        [
                            'name' => 'wait_for_new_mail_seconds',
                            'label' => 'Auf neue Mail warten (Sekunden)',
                            'type' => 'number',
                            'min' => 0,
                            'max' => 3600,
                            'step' => 5,
                            'placeholder' => '60',
                            'help' => 'Der Scan wiederholt sich im 5-Sekunden-Takt, bis eine neue passende Mail gefunden wurde oder die Zeit ablaeuft.',
                            'tab' => 'Zeit',
                        ],
                        [
                            'name' => 'max_items',
                            'label' => 'Maximale Treffer',
                            'type' => 'number',
                            'min' => 1,
                            'max' => 200,
                            'step' => 1,
                            'placeholder' => '30',
                            'default' => '50',
                            'tab' => 'Ausgabe',
                        ],
                    ],
                ],
            ],
            'mail.list_search_loop' => [
                'label' => 'Mail-Liste durchsuchen',
                'kind' => 'browser',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/mail/list_search_loop.cjs',
                'timeout_seconds' => 120,
                'description' => 'Durchlaeuft ein zuvor erzeugtes Mail-Array, oeffnet passende Listeneintraege und speichert die gefundene Mail oder einen extrahierten Wert unter frei waehlbarem Namen.',
                'form' => [
                    'selector' => true,
                    'selector_required' => false,
                    'selector_label' => 'Mail-Body-Selector',
                    'selector_placeholder' => '[role=document], article, [class*=mail-body] oder leer fuer Fallbacks',
                    'value' => true,
                    'value_required' => false,
                    'value_label' => 'Suchtext',
                    'value_placeholder' => 'Instagram, Sicherheitscode oder Domain',
                    'url' => false,
                    'success_payload' => false,
                    'failure_payload' => false,
                    'extra_fields' => [
                        [
                            'name' => 'input_array_name',
                            'label' => 'Eingabe-Array',
                            'placeholder' => 'inbox_mails',
                            'default' => 'inbox_mails',
                            'tab' => 'Quelle',
                        ],
                        [
                            'name' => 'search_fields',
                            'label' => 'Suchfelder',
                            'placeholder' => 'subject,title,sender,preview,body',
                            'default' => 'subject,title,sender,preview,body',
                            'help' => "Mehrere Werte als Komma-Liste oder Array-Schreibweise: ['subject', 'body']",
                            'tab' => 'Filter',
                        ],
                        [
                            'name' => 'subject_selector',
                            'label' => 'Betreff-Selector',
                            'placeholder' => '[class*=subject]',
                            'help' => 'Optional, falls Betreff nach dem Oeffnen der Mail aus dem DOM gelesen werden soll.',
                            'tab' => 'Filter',
                        ],
                        [
                            'name' => 'subject_filter',
                            'label' => 'Betreff muss enthalten',
                            'placeholder' => "['queued', 'running', 'waiting'] oder queued",
                            'help' => 'Optional. Wenn Betreff- oder Titelfilter passt, landet die Mail im Trefferarray.',
                            'span' => 'full',
                            'tab' => 'Filter',
                        ],
                        [
                            'name' => 'title_selector',
                            'label' => 'Titel-Selector',
                            'placeholder' => '[title], [class*=title]',
                            'help' => 'Optional, falls der Titel nach dem Oeffnen der Mail aus dem DOM gelesen werden soll.',
                            'tab' => 'Filter',
                        ],
                        [
                            'name' => 'title_filter',
                            'label' => 'Titel muss enthalten',
                            'placeholder' => "['queued', 'running', 'waiting'] oder queued",
                            'help' => 'Optional. Wenn Betreff- oder Titelfilter passt, landet die Mail im Trefferarray.',
                            'span' => 'full',
                            'tab' => 'Filter',
                        ],
                        [
                            'name' => 'output_mail_name',
                            'label' => 'Ausgabe-Mail',
                            'placeholder' => 'matched_mail',
                            'default' => 'matched_mail',
                            'tab' => 'Ausgabe',
                        ],
                        [
                            'name' => 'output_value_name',
                            'label' => 'Ausgabe-Wert',
                            'placeholder' => 'verification_code oder mail_body',
                            'help' => 'Optional. Wenn gesetzt, wird ein extrahierter Wert oder der konfigurierte Mail-Inhalt unter diesem Namen gespeichert.',
                            'tab' => 'Ausgabe',
                        ],
                        [
                            'name' => 'output_value_source',
                            'label' => 'Quelle fuer Ausgabe-Wert',
                            'placeholder' => 'body',
                            'default' => 'body',
                            'help' => 'Wird genutzt, wenn keine Regex/Extraktion aktiv ist. Beispiele: body, subject, sender, preview.',
                            'tab' => 'Ausgabe',
                        ],
                        [
                            'name' => 'max_age_minutes',
                            'label' => 'Mail maximal alt (Minuten)',
                            'type' => 'number',
                            'min' => 0,
                            'max' => 10080,
                            'step' => 1,
                            'placeholder' => '15',
                            'tab' => 'Laufzeit',
                        ],
                        [
                            'name' => 'max_open_count',
                            'label' => 'Maximal oeffnen',
                            'type' => 'number',
                            'min' => 1,
                            'max' => 50,
                            'step' => 1,
                            'placeholder' => '8',
                            'default' => '8',
                            'tab' => 'Laufzeit',
                        ],
                        [
                            'name' => 'open_wait_ms',
                            'label' => 'Warten nach Oeffnen (ms)',
                            'type' => 'number',
                            'min' => 0,
                            'max' => 10000,
                            'step' => 100,
                            'placeholder' => '900',
                            'default' => '900',
                            'tab' => 'Laufzeit',
                        ],
                        [
                            'name' => 'stop_on_first_match',
                            'label' => 'Beim ersten Treffer stoppen',
                            'placeholder' => 'true',
                            'default' => 'true',
                            'help' => 'true/false',
                            'tab' => 'Laufzeit',
                        ],
                        [
                            'name' => 'regex',
                            'label' => 'Regex fuer Wert',
                            'placeholder' => '\\b\\d{6}\\b',
                            'help' => 'Optional. Wenn gesetzt, wird aus dem Mail-Body ein Wert extrahiert.',
                            'tab' => 'Extraktion',
                        ],
                    ],
                ],
            ],
            'mail.list_action_loop' => [
                'label' => 'Mail-Liste: Aktion je Mail ausfuehren',
                'kind' => 'browser',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/mail/list_action_loop.cjs',
                'timeout_seconds' => 600,
                'description' => 'Durchlaeuft ein zuvor gescanntes Mail-Array, oeffnet jede Mail und fuehrt eine oder mehrere konfigurierbare Klickaktionen aus, z. B. Loeschen und Bestaetigen.',
                'form' => [
                    'selector' => true,
                    'selector_required' => false,
                    'selector_label' => 'Aktions-Selector',
                    'selector_placeholder' => 'button[aria-label*=delete i], text=Loeschen',
                    'value' => false,
                    'url' => false,
                    'success_payload' => false,
                    'failure_payload' => false,
                    'extra_fields' => [
                        [
                            'name' => 'input_array_name',
                            'label' => 'Eingabe-Mail-Array',
                            'placeholder' => 'inbox_mails',
                            'default' => 'inbox_mails',
                            'tab' => 'Quelle & Oeffnen',
                        ],
                        [
                            'name' => 'open_selector',
                            'label' => 'Mail-Oeffnen-Selector',
                            'placeholder' => '[role=row], [data-message-id]',
                            'help' => 'Optional. Leer verwendet den beim Inbox-Scan gespeicherten Listitem-Selector.',
                            'tab' => 'Quelle & Oeffnen',
                        ],
                        [
                            'name' => 'open_wait_ms',
                            'label' => 'Warten nach Oeffnen (ms)',
                            'type' => 'number',
                            'min' => 0,
                            'max' => 30000,
                            'step' => 100,
                            'default' => '700',
                            'tab' => 'Quelle & Oeffnen',
                        ],
                        [
                            'name' => 'confirm_selector',
                            'label' => 'Bestaetigungs-Selector',
                            'placeholder' => 'button:has-text("Endgueltig loeschen")',
                            'help' => 'Optionaler zweiter Klick nach dem Aktions-Selector.',
                            'tab' => 'Aktionen',
                        ],
                        [
                            'name' => 'action_steps',
                            'label' => 'Weitere Aktionsschritte (JSON)',
                            'type' => 'textarea',
                            'rows' => 7,
                            'span' => 'full',
                            'placeholder' => "[\n  {\"selector\":\"button[aria-label*=delete i]\",\"wait_ms\":500},\n  {\"selector\":\"button:has-text('Bestaetigen')\",\"wait_ms\":700}\n]",
                            'help' => 'Wenn gesetzt, ersetzt diese Reihenfolge Aktions- und Bestaetigungs-Selector. required:false erlaubt optionale Schritte.',
                            'tab' => 'Aktionen',
                        ],
                        [
                            'name' => 'return_selector',
                            'label' => 'Zurueck-zur-Liste-Selector',
                            'placeholder' => 'button[aria-label*=back i], text=Posteingang',
                            'help' => 'Optional. Nur erforderlich, wenn die Aktion nicht automatisch zur Mail-Liste zurueckkehrt.',
                            'tab' => 'Aktionen',
                        ],
                        [
                            'name' => 'action_wait_ms',
                            'label' => 'Warten je Aktion (ms)',
                            'type' => 'number',
                            'min' => 0,
                            'max' => 30000,
                            'step' => 100,
                            'default' => '500',
                            'tab' => 'Laufzeit',
                        ],
                        [
                            'name' => 'action_timeout_ms',
                            'label' => 'Selector-Timeout (ms)',
                            'type' => 'number',
                            'min' => 250,
                            'max' => 120000,
                            'step' => 250,
                            'default' => '10000',
                            'tab' => 'Laufzeit',
                        ],
                        [
                            'name' => 'max_items',
                            'label' => 'Maximal verarbeiten',
                            'type' => 'number',
                            'min' => 1,
                            'max' => 200,
                            'default' => '50',
                            'tab' => 'Laufzeit',
                        ],
                        [
                            'name' => 'continue_on_error',
                            'label' => 'Nach Einzelfehler fortsetzen',
                            'placeholder' => 'true',
                            'default' => 'true',
                            'tab' => 'Laufzeit',
                        ],
                        [
                            'name' => 'output_array_name',
                            'label' => 'Ergebnis-Array',
                            'placeholder' => 'mail_action_results',
                            'default' => 'mail_action_results',
                            'tab' => 'Ergebnis',
                        ],
                    ],
                ],
            ],
            'mail.extract_value' => [
                'label' => 'Wert aus Mail ermitteln',
                'kind' => 'browser',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/mail/extract_value.cjs',
                'timeout_seconds' => 45,
                'description' => 'Extrahiert per Regex, Code-Heuristik oder Contains-Regel einen Wert aus einer geoeffneten Mail oder einer Workflow-Variable.',
                'form' => [
                    'selector' => true,
                    'selector_required' => false,
                    'selector_label' => 'Mail-Body-Selector',
                    'selector_placeholder' => '[role=document], article, [class*=mail-body] oder leer fuer sichtbaren Text',
                    'value' => true,
                    'value_required' => false,
                    'value_label' => 'Regex oder Optionen JSON',
                    'value_placeholder' => '\\b\\d{6}\\b oder {"source":"workflow_variables.matched_mail.body","output_value_name":"verification_code"}',
                    'url' => false,
                    'success_payload' => true,
                    'success_payload_label' => 'Ausgabe/Extraktion JSON',
                    'success_payload_placeholder' => '{"output_value_name":"verification_code","extract_mode":"verification_code","required":true}',
                    'failure_payload' => false,
                ],
            ],
            'browser.scroll' => [
                'label' => 'Seite oder Container scrollen',
                'kind' => 'browser',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/browser/scroll.cjs',
                'timeout_seconds' => 60,
                'description' => 'Scrollt eine Seite oder einen Container kontrolliert, laedt Lazy Content nach und stoppt optional bei einem Ziel-Selector oder unveraendertem Inhalt.',
                'form' => [
                    'selector' => true,
                    'selector_required' => false,
                    'selector_label' => 'Scroll-Container (optional)',
                    'selector_placeholder' => 'leer = Browserfenster, sonst z. B. .results',
                    'value' => false,
                    'url' => false,
                    'success_payload' => false,
                    'failure_payload' => false,
                    'extra_fields' => [
                        ['name' => 'direction', 'label' => 'Richtung', 'default' => 'down', 'placeholder' => 'down oder up', 'tab' => 'Scroll'],
                        ['name' => 'pixels', 'label' => 'Pixel pro Runde', 'type' => 'number', 'min' => 1, 'max' => 100000, 'default' => '600', 'tab' => 'Scroll'],
                        ['name' => 'steps', 'label' => 'Runden', 'type' => 'number', 'min' => 1, 'max' => 1000, 'default' => '1', 'tab' => 'Scroll'],
                        ['name' => 'delay_ms_between_steps', 'label' => 'Pause zwischen Runden (ms)', 'type' => 'number', 'min' => 0, 'max' => 60000, 'default' => '250', 'tab' => 'Scroll'],
                        ['name' => 'until_selector', 'label' => 'Stop-Selector (optional)', 'placeholder' => '.last-result, [data-loaded=true]', 'tab' => 'Stop'],
                        ['name' => 'max_rounds', 'label' => 'Maximale Runden', 'type' => 'number', 'min' => 1, 'max' => 1000, 'default' => '20', 'tab' => 'Stop'],
                        ['name' => 'stop_if_no_change', 'label' => 'Ohne Aenderung stoppen', 'default' => 'true', 'placeholder' => 'true oder false', 'tab' => 'Stop'],
                    ],
                ],
            ],
            'loop.for_each_element' => [
                'label' => 'Fuer jedes DOM-Element',
                'kind' => 'browser',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/loop/for_each_element.cjs',
                'timeout_seconds' => 30,
                'description' => 'Iteriert Treffer eines konfigurierbaren DOM-Selectors. Der aktuelle Element-Handle bleibt privat im Node-Kontext; Status und Index werden als Workflow-Variablen bereitgestellt.',
                'form' => [
                    'selector' => true,
                    'selector_label' => 'Treffer-Selector',
                    'selector_placeholder' => '#search .g, .product-card, [data-result]',
                    'value' => false,
                    'url' => false,
                    'success_payload' => false,
                    'failure_payload' => false,
                    'extra_fields' => [
                        ['name' => 'limit', 'label' => 'Maximale Treffer', 'type' => 'number', 'min' => 0, 'max' => 10000, 'default' => '0', 'help' => '0 verarbeitet alle Treffer.', 'tab' => 'Schleife'],
                        ['name' => 'offset', 'label' => 'Treffer ueberspringen', 'type' => 'number', 'min' => 0, 'max' => 10000, 'default' => '0', 'tab' => 'Schleife'],
                        ['name' => 'only_visible', 'label' => 'Nur sichtbare Elemente', 'default' => 'true', 'placeholder' => 'true oder false', 'tab' => 'Schleife'],
                        ['name' => 'store_current_element_as', 'label' => 'Aktuelles Element als', 'default' => 'current_result', 'placeholder' => 'current_result', 'tab' => 'Variablen'],
                        ['name' => 'store_index_as', 'label' => 'Index als', 'default' => 'result_index', 'placeholder' => 'result_index', 'tab' => 'Variablen'],
                        ['name' => 'success_target', 'label' => 'Zielkarte je Treffer', 'placeholder' => 'Karten-Key von read_element_fields', 'help' => 'Optional. Ohne Eingabe wird die normale Erfolgsroute verwendet.', 'tab' => 'Routen'],
                        ['name' => 'empty_target', 'label' => 'Zielkarte wenn fertig/leer', 'placeholder' => 'Karten-Key von array_length oder workflow_return', 'tab' => 'Routen'],
                        ['name' => 'error_target', 'label' => 'Zielkarte bei Fehler', 'placeholder' => 'Karten-Key der Fehlerbehandlung', 'tab' => 'Routen'],
                    ],
                ],
            ],
            'browser.read_element_fields' => [
                'label' => 'Felder aus aktuellem Element lesen',
                'kind' => 'browser',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/browser/read_element_fields.cjs',
                'timeout_seconds' => 30,
                'description' => 'Liest mehrere konfigurierbare Text-, Link-, HTML-, Attribut- oder Exists-Felder aus dem aktuellen Loop-Element und speichert ein strukturiertes Objekt.',
                'form' => [
                    'selector' => false,
                    'value' => false,
                    'url' => false,
                    'success_payload' => false,
                    'failure_payload' => false,
                    'extra_fields' => [
                        ['name' => 'scope_variable', 'label' => 'Loop-Scope', 'default' => 'current_result', 'placeholder' => 'current_result', 'tab' => 'Quelle'],
                        ['name' => 'output_variable', 'label' => 'Ausgabevariable', 'default' => 'current_result', 'placeholder' => 'current_result', 'help' => 'Darf dem Scope-Namen entsprechen; der DOM-Handle bleibt separat erhalten.', 'tab' => 'Quelle'],
                        [
                            'name' => 'fields',
                            'label' => 'Felddefinitionen (JSON)',
                            'type' => 'textarea',
                            'rows' => 9,
                            'span' => 'full',
                            'placeholder' => '[{"name":"titel","selector":"h3","type":"text","required":true},{"name":"url","selector":"a","type":"href","required":true},{"name":"description","selector":".description","fallback_selectors":[".snippet"],"type":"text"}]',
                            'help' => 'Typen: text, inner_text, href, html, attribute, exists. Optional: attribute_name, multiple, join_with, fallback_selectors, default_value, trim, normalize_whitespace.',
                            'tab' => 'Felder',
                        ],
                    ],
                ],
            ],
            'data.append_to_array' => [
                'label' => 'Objekt an Array anhaengen',
                'kind' => 'data',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/data/append_to_array.cjs',
                'timeout_seconds' => 15,
                'description' => 'Haengt eine Workflow-Variable an ein benanntes Array an, optional mit Deduplizierung und maximaler Laenge.',
                'form' => [
                    'selector' => false,
                    'value' => false,
                    'url' => false,
                    'success_payload' => false,
                    'failure_payload' => false,
                    'extra_fields' => [
                        ['name' => 'array_name', 'label' => 'Array-Name', 'default' => 'top_results', 'placeholder' => 'top_results', 'tab' => 'Array'],
                        ['name' => 'value_from_variable', 'label' => 'Wert aus Variable', 'default' => 'current_result', 'placeholder' => 'current_result', 'tab' => 'Array'],
                        ['name' => 'dedupe_by', 'label' => 'Deduplizieren nach', 'placeholder' => 'url', 'help' => 'Optionaler Objektpfad, z. B. url oder product.id.', 'tab' => 'Array'],
                        ['name' => 'max_items', 'label' => 'Maximale Eintraege', 'type' => 'number', 'min' => 0, 'max' => 100000, 'default' => '0', 'help' => '0 bedeutet unbegrenzt.', 'tab' => 'Array'],
                    ],
                ],
            ],
            'decision.array_length' => [
                'label' => 'IF Array-Laenge pruefen',
                'kind' => 'data',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/decision/array_length.cjs',
                'timeout_seconds' => 15,
                'description' => 'Prueft die Anzahl gesammelter Array-Eintraege mit >=, >, =, !=, < oder <= und verzweigt optional dynamisch.',
                'form' => [
                    'selector' => false,
                    'value' => false,
                    'url' => false,
                    'success_payload' => false,
                    'failure_payload' => false,
                    'extra_fields' => [
                        ['name' => 'array_name', 'label' => 'Array-Name', 'default' => 'top_results', 'placeholder' => 'top_results', 'tab' => 'Bedingung'],
                        ['name' => 'operator', 'label' => 'Operator', 'default' => '>=', 'placeholder' => '>=', 'tab' => 'Bedingung'],
                        ['name' => 'compare_value', 'label' => 'Vergleichswert', 'type' => 'number', 'min' => 0, 'max' => 100000, 'default' => '3', 'tab' => 'Bedingung'],
                        ['name' => 'success_target', 'label' => 'Zielkarte wenn erfuellt', 'placeholder' => 'Karten-Key', 'tab' => 'Routen'],
                        ['name' => 'error_target', 'label' => 'Zielkarte wenn nicht erfuellt', 'placeholder' => 'Karten-Key', 'tab' => 'Routen'],
                    ],
                ],
            ],
            'browser.read_searchengine_result' => [
                'label' => 'Suchmaschinentreffer lesen',
                'kind' => 'browser',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/browser/read_searchengine_result.cjs',
                'timeout_seconds' => 30,
                'description' => 'Komfortabler, aber engine-unabhaengiger Wrapper fuer Titel, URL, Beschreibung, Site-Name und Breadcrumb eines aktuellen Loop-Treffers.',
                'form' => [
                    'selector' => false,
                    'value' => false,
                    'url' => false,
                    'success_payload' => false,
                    'failure_payload' => false,
                    'extra_fields' => [
                        ['name' => 'scope_variable', 'label' => 'Loop-Scope', 'default' => 'current_result', 'placeholder' => 'current_result', 'tab' => 'Quelle'],
                        ['name' => 'output_variable', 'label' => 'Ausgabevariable', 'default' => 'current_result', 'placeholder' => 'current_result', 'tab' => 'Quelle'],
                        ['name' => 'title_selector', 'label' => 'Titel-Selector', 'default' => 'h3', 'placeholder' => 'h3, .result-title', 'tab' => 'Selektoren'],
                        ['name' => 'link_selector', 'label' => 'Link-Selector', 'default' => 'a', 'placeholder' => 'a[href]', 'tab' => 'Selektoren'],
                        ['name' => 'description_selector', 'label' => 'Description-Selector', 'placeholder' => '.VwiC3b, .snippet, .description', 'tab' => 'Selektoren'],
                        ['name' => 'site_name_selector', 'label' => 'Site-Name-Selector', 'placeholder' => '.site-name', 'tab' => 'Selektoren'],
                        ['name' => 'breadcrumb_selector', 'label' => 'Breadcrumb-Selector', 'placeholder' => '.breadcrumb', 'tab' => 'Selektoren'],
                        ['name' => 'fallbacks', 'label' => 'Fallbacks (JSON)', 'type' => 'textarea', 'rows' => 5, 'span' => 'full', 'placeholder' => '{"title":["[role=heading]"],"link":["a[href]"],"description":[".VwiC3b",".snippet"]}', 'tab' => 'Fallbacks'],
                        ['name' => 'visible_only', 'label' => 'Nur sichtbare Felder', 'default' => 'true', 'placeholder' => 'true oder false', 'tab' => 'Optionen'],
                        ['name' => 'normalize_url', 'label' => 'Relative URLs normalisieren', 'default' => 'true', 'placeholder' => 'true oder false', 'tab' => 'Optionen'],
                        ['name' => 'trim_text', 'label' => 'Text trimmen', 'default' => 'true', 'placeholder' => 'true oder false', 'tab' => 'Optionen'],
                    ],
                ],
            ],
            'browser.find_inputs' => [
                'label' => 'Input-Felder suchen',
                'kind' => 'input',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/browser/find_inputs.cjs',
                'timeout_seconds' => 45,
                'description' => 'Sammelt sichtbare Eingabefelder mit Name, Label, Placeholder und Selector-Kandidaten.',
                'form' => [
                    'selector' => false,
                    'value' => false,
                    'url' => false,
                    'success_payload' => true,
                    'failure_payload' => true,
                ],
            ],
            'browser.find_element' => [
                'label' => 'Element ermitteln',
                'kind' => 'browser',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/browser/find_element.cjs',
                'timeout_seconds' => 45,
                'description' => 'Sucht ein Element per Selector, Text oder Rolle und liefert Treffer-Metadaten.',
                'form' => [
                    'selector' => true,
                    'selector_label' => 'Selector oder Text',
                    'selector_placeholder' => 'button[type=submit], #login oder text=Weiter',
                    'value' => false,
                    'url' => false,
                    'success_payload' => true,
                    'failure_payload' => true,
                ],
            ],
            'browser.hover' => [
                'label' => 'Element hovern',
                'kind' => 'browser',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/browser/hover.cjs',
                'timeout_seconds' => 30,
                'description' => 'Bewegt den Cursor auf ein Element und haelt den Hover-Zustand fuer folgende Such-, Klick- und Eingabe-Tasks aktiv.',
                'form' => [
                    'selector' => true,
                    'selector_label' => 'Hover-Selector oder Text',
                    'selector_placeholder' => '[aria-haspopup=true], button:has-text("Mehr") oder text=Menue',
                    'timeout' => true,
                    'timeout_label' => 'Suchdauer in Sekunden',
                    'timeout_help' => 'Wie lange nach dem Hover-Element gesucht wird.',
                    'timeout_min' => 1,
                    'timeout_max' => 3600,
                    'value' => false,
                    'url' => false,
                    'success_payload' => true,
                    'failure_payload' => true,
                    'extra_fields' => [
                        [
                            'name' => 'settle_ms',
                            'label' => 'Warten nach Hover (ms)',
                            'type' => 'number',
                            'min' => 0,
                            'max' => 10000,
                            'step' => 50,
                            'placeholder' => '250',
                            'default' => '250',
                            'help' => 'Kurze Wartezeit, damit durch Hover sichtbare Elemente gerendert werden.',
                            'tab' => 'Hover',
                        ],
                        [
                            'name' => 'release_after_click',
                            'label' => 'Cursor nach Klick entfernen',
                            'placeholder' => 'true',
                            'default' => 'true',
                            'help' => 'true bewegt den Cursor nach einem erfolgreichen Folge-Klick weg. false haelt den Hover fuer weitere Tasks.',
                            'tab' => 'Hover',
                        ],
                    ],
                ],
            ],
            'decision.element_exists' => [
                'label' => 'IF Element vorhanden',
                'kind' => 'browser',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/decision/element_exists.cjs',
                'timeout_seconds' => 15,
                'description' => 'Prueft, ob ein sichtbares Element existiert. Treffer folgen der Erfolgsroute, fehlende Elemente der Fehlerroute.',
                'form' => [
                    'selector' => true,
                    'selector_label' => 'IF-Selector',
                    'selector_placeholder' => 'button:has(span:has-text("Login")), #mailbox',
                    'timeout' => true,
                    'timeout_label' => 'Suchdauer in Sekunden',
                    'timeout_help' => 'Wie lange nach dem Element gesucht wird. Fuer schnelle Abfragen z. B. 1-3 Sekunden verwenden.',
                    'timeout_min' => 1,
                    'timeout_max' => 3600,
                    'value' => false,
                    'url' => false,
                    'success_payload' => false,
                    'failure_payload' => false,
                ],
            ],
            'decision.variable' => [
                'label' => 'IF Eingabevariable pruefen',
                'kind' => 'data',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/decision/variable.cjs',
                'timeout_seconds' => 15,
                'description' => 'Prueft Werte aus Workflow-Eingaben oder Workflow-Variablen. Erfuellt folgt der Erfolgsroute, nicht erfuellt der Fehlerroute.',
                'form' => [
                    'selector' => false,
                    'value' => false,
                    'url' => false,
                    'success_payload' => false,
                    'failure_payload' => false,
                    'extra_fields' => [
                        [
                            'name' => 'variable_path',
                            'label' => 'Variablenpfad',
                            'placeholder' => 'browser_window oder Mail-Inbox-Liste-Scan.subject_filter',
                            'help' => 'Wird direkt aus den durch Workflow-Eingaben pruefen erzeugten Workflow-Variablen gelesen.',
                            'span' => 'full',
                            'required' => true,
                            'tab' => 'Bedingung',
                        ],
                        [
                            'name' => 'operator',
                            'label' => 'Operator',
                            'placeholder' => 'exists',
                            'default' => 'exists',
                            'help' => 'exists, missing, equals, not_equals, contains, truthy, falsy oder browser_window_open.',
                            'tab' => 'Bedingung',
                        ],
                        [
                            'name' => 'compare_value',
                            'label' => 'Vergleichswert',
                            'placeholder' => 'main, true, 15 oder JSON',
                            'help' => 'Nur fuer equals, not_equals oder contains erforderlich.',
                            'tab' => 'Bedingung',
                        ],
                    ],
                ],
            ],
            'browser.click' => [
                'label' => 'Button/Link klicken',
                'kind' => 'browser',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/browser/click.cjs',
                'timeout_seconds' => 60,
                'description' => 'Klickt ein Element per Selector oder Text und gibt den Folgezustand weiter.',
                'form' => [
                    'selector' => true,
                    'selector_label' => 'Selector oder Klicktext',
                    'selector_placeholder' => 'button[type=submit], a[href*=next] oder text=Weiter',
                    'value' => false,
                    'url' => false,
                    'success_payload' => true,
                    'failure_payload' => true,
                ],
            ],
            'input.fill_field' => [
                'label' => 'Input-Feld fuellen',
                'kind' => 'input',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/input/fill_field.cjs',
                'timeout_seconds' => 60,
                'description' => 'Fuellt ein konkretes oder heuristisch gefundenes Eingabefeld mit variablem Wert.',
                'form' => [
                    'selector' => true,
                    'selector_label' => 'Selector',
                    'selector_placeholder' => 'input[name=email], #password',
                    'value' => true,
                    'value_label' => 'Datenquelle oder Wert',
                    'value_placeholder' => 'person.email, person.password oder fester Wert',
                    'url' => false,
                    'success_payload' => true,
                    'failure_payload' => true,
                ],
            ],
            'input.submit' => [
                'label' => 'Formular absenden',
                'kind' => 'input',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/input/submit.cjs',
                'timeout_seconds' => 60,
                'description' => 'Klickt auf einen passenden Submit-Button oder sendet das naechste Formular ab.',
                'form' => [
                    'selector' => true,
                    'selector_label' => 'Submit-Selector',
                    'selector_placeholder' => 'button[type=submit] oder text=Absenden',
                    'value' => false,
                    'url' => false,
                    'success_payload' => true,
                    'failure_payload' => true,
                ],
            ],
            'wait.selector' => [
                'label' => 'Auf Element warten',
                'kind' => 'wait',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/wait/selector.cjs',
                'timeout_seconds' => 90,
                'description' => 'Wartet auf ein sichtbares Element und liefert je nach Treffer einen Status.',
                'form' => [
                    'selector' => true,
                    'selector_label' => 'Selector',
                    'selector_placeholder' => '#mailbox, [data-ready=true]',
                    'value' => false,
                    'url' => false,
                    'success_payload' => true,
                    'failure_payload' => true,
                ],
            ],
            'wait.seconds' => [
                'label' => 'Warten',
                'kind' => 'wait',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/wait/seconds.cjs',
                'timeout_seconds' => 120,
                'description' => 'Wartet eine definierte Zeit und leitet danach weiter.',
                'form' => [
                    'selector' => false,
                    'value' => true,
                    'value_label' => 'Sekunden',
                    'value_placeholder' => '5',
                    'url' => false,
                    'success_payload' => false,
                    'failure_payload' => false,
                ],
            ],
            'wait.status' => [
                'label' => 'Status auswerten',
                'kind' => 'wait',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/wait/status.cjs',
                'timeout_seconds' => 30,
                'description' => 'Prueft DOM/Text/URL gegen Statusregeln und gibt success, partial, failed oder timeout zurueck.',
                'form' => [
                    'selector' => false,
                    'value' => true,
                    'value_label' => 'Statusregeln',
                    'value_placeholder' => '[{"source":"text","contains":"Willkommen","status":"success"}]',
                    'url' => false,
                    'success_payload' => true,
                    'failure_payload' => true,
                ],
            ],
            'mail.generate_address' => [
                'label' => 'Wunsch-Mailadresse generieren',
                'kind' => 'input',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/mail/generate_address.cjs',
                'timeout_seconds' => 45,
                'description' => 'Erstellt aus Vorname, Nachname und Zufallskombinationen einen Username und traegt ihn in das Registrierungsfeld ein.',
                'form' => [
                    'selector' => true,
                    'selector_label' => 'Username/E-Mail-Selector',
                    'selector_placeholder' => 'input[name*=username], input[type=email]',
                    'value' => false,
                    'url' => false,
                    'success_payload' => true,
                    'failure_payload' => true,
                ],
            ],
            'mail.fill_address' => [
                'label' => 'Mailadresse eintragen',
                'kind' => 'input',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/mail/fill_address.cjs',
                'timeout_seconds' => 45,
                'description' => 'Traegt den aktuellen Wunsch-Username oder die Wunsch-Mailadresse in das Registrierungsfeld ein.',
                'form' => [
                    'selector' => true,
                    'selector_label' => 'E-Mail/Username-Selector',
                    'selector_placeholder' => 'input[name*=username], input[type=email]',
                    'value' => false,
                    'url' => false,
                    'success_payload' => true,
                    'failure_payload' => true,
                ],
            ],
            'mail.check_address_availability' => [
                'label' => 'Mailadresse pruefen',
                'kind' => 'wait',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/mail/check_address_availability.cjs',
                'timeout_seconds' => 90,
                'description' => 'Prueft Provider-Feedback und probiert bei belegter Adresse automatisch weitere Kandidaten.',
                'form' => [
                    'selector' => true,
                    'selector_label' => 'E-Mail/Username-Selector',
                    'selector_placeholder' => 'input[name*=username], input[type=email]',
                    'value' => false,
                    'url' => false,
                    'success_payload' => true,
                    'failure_payload' => true,
                ],
            ],
            'mail.generate_password' => [
                'label' => 'Wunschpasswort generieren',
                'kind' => 'input',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/mail/generate_password.cjs',
                'timeout_seconds' => 45,
                'description' => 'Generiert ein neues Passwort, traegt es ein und stellt generated-password sowie new_password bereit.',
                'form' => [
                    'selector' => true,
                    'selector_label' => 'Passwort-Selector',
                    'selector_placeholder' => 'input[type=password]',
                    'value' => false,
                    'url' => false,
                    'success_payload' => true,
                    'failure_payload' => true,
                ],
            ],
            'data.validate_inputs' => [
                'label' => 'Workflow-Eingaben pruefen',
                'kind' => 'data',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/data/validate_inputs.cjs',
                'timeout_seconds' => 15,
                'description' => 'Prueft Start-/Eingabewerte, setzt optionale Defaults und kann Werte per Tasktitel.inputid automatisch in folgende Tasks uebernehmen.',
                'form' => [
                    'selector' => false,
                    'value' => false,
                    'url' => false,
                    'success_payload' => false,
                    'failure_payload' => true,
                    'extra_fields' => [
                        [
                            'name' => 'input_definitions',
                            'label' => 'Eingabewerte',
                            'type' => 'textarea',
                            'rows' => 8,
                            'span' => 'full',
                            'placeholder' => "[\n  {\"name\":\"browser_window\",\"type\":\"browser_window\",\"required\":false},\n  {\"name\":\"Mail-Inbox-Liste-Scan.subject_filter\",\"required\":false},\n  {\"name\":\"Mail-Inbox-Liste-Scan.titel_filter\",\"required\":false},\n  {\"name\":\"Mail-Inbox-Liste-Scan.max_age_minutes\",\"type\":\"number\",\"required\":false},\n  {\"name\":\"Mail-Inbox-Liste-Scan.mail_ids\",\"required\":false}\n]\n\nEine abschliessende Kommastelle vor ] wird toleriert.",
                            'help' => 'Ohne source wird der Eingabewert unter demselben Namen gesucht. Nur gesetzte Werte ueberschreiben folgende Tasks. titel_filter wird automatisch auf title_filter abgebildet.',
                            'tab' => 'Eingaben',
                        ],
                        [
                            'name' => 'output_group',
                            'label' => 'Ausgabe-Gruppe',
                            'placeholder' => 'workflow_inputs',
                            'default' => 'workflow_inputs',
                            'help' => 'Alle geprueften Werte werden zusaetzlich als Objekt unter diesem Workflow-Variablennamen gespeichert.',
                            'tab' => 'Ausgabe',
                        ],
                    ],
                ],
            ],
            'data.read_account_data' => [
                'label' => 'Accountdaten lesen',
                'kind' => 'data',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/data/read_account_data.cjs',
                'php_handler' => 'App\\Services\\Workflows\\Tasks\\ReadAccountDataTask@handle',
                'timeout_seconds' => 15,
                'description' => 'Extrahiert Accountdaten aus Workflow-, Persona- oder Node-Ergebnissen.',
                'form' => [
                    'selector' => false,
                    'value' => false,
                    'url' => false,
                    'success_payload' => true,
                    'failure_payload' => true,
                ],
            ],
            'data.resolve_person' => [
                'label' => 'Person-Daten ermitteln',
                'kind' => 'data',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/data/resolve_person.cjs',
                'php_handler' => 'App\\Services\\Workflows\\Tasks\\ResolvePersonDataTask@handle',
                'timeout_seconds' => 15,
                'description' => 'Liest Persona-Stammdaten und stellt sie als Payload fuer weitere Tasks bereit.',
                'form' => [
                    'selector' => false,
                    'value' => false,
                    'url' => false,
                    'success_payload' => true,
                    'failure_payload' => false,
                ],
            ],
            'data.read_login_data' => [
                'label' => 'Login-Daten lesen',
                'kind' => 'data',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/data/read_login_data.cjs',
                'php_handler' => 'App\\Services\\Workflows\\Tasks\\ReadLoginDataTask@handle',
                'timeout_seconds' => 15,
                'description' => 'Bereitet Provider, E-Mail, Benutzername, Passwort und Webmail-URL fuer Login-Tasks vor.',
                'form' => [
                    'selector' => false,
                    'value' => false,
                    'url' => false,
                    'success_payload' => true,
                    'failure_payload' => true,
                ],
            ],
            'data.persist_mail_account' => [
                'label' => 'Workflow-/Mail-Accountdaten speichern',
                'kind' => 'data',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/data/persist_mail_account.cjs',
                'php_handler' => 'App\\Services\\Workflows\\Tasks\\PersistMailAccountTask@handle',
                'timeout_seconds' => 30,
                'description' => 'Speichert E-Mail, Passwort, Provider und weitere Werte als Workflow-Variablen und optional am Mail-Account der Persona.',
                'form' => [
                    'selector' => false,
                    'value' => false,
                    'url' => false,
                    'success_payload' => false,
                    'failure_payload' => true,
                    'extra_fields' => [
                        [
                            'name' => 'persist_account',
                            'label' => 'Mail-Account persistieren',
                            'placeholder' => 'true',
                            'default' => 'true',
                            'help' => 'true speichert die Accountdaten verschluesselt an der Persona. false speichert nur Workflow-Variablen.',
                            'tab' => 'Speichern',
                        ],
                        [
                            'name' => 'group_variable',
                            'label' => 'Gruppenvariable',
                            'placeholder' => 'email_account',
                            'default' => 'email_account',
                            'help' => 'Alle erkannten Werte werden zusaetzlich als Objekt unter diesem Workflow-Variablennamen gespeichert.',
                            'tab' => 'Speichern',
                        ],
                        [
                            'name' => 'field_map',
                            'label' => 'Feldzuordnung',
                            'type' => 'textarea',
                            'rows' => 5,
                            'span' => 'full',
                            'placeholder' => '{"email":"account.email","password":"generated_password","provider":"literal:proton"}',
                            'help' => 'Optional als JSON oder zeilenweise key=quelle. Quellen koennen Context-Pfade oder literal:Wert sein.',
                            'tab' => 'Speichern',
                        ],
                        [
                            'name' => 'email_source',
                            'label' => 'E-Mail Quelle',
                            'placeholder' => 'account.email',
                            'tab' => 'Einzelwerte',
                        ],
                        [
                            'name' => 'email_variable',
                            'label' => 'E-Mail Variable',
                            'placeholder' => 'email',
                            'default' => 'email',
                            'tab' => 'Einzelwerte',
                        ],
                        [
                            'name' => 'username_source',
                            'label' => 'Benutzername Quelle',
                            'placeholder' => 'account.username',
                            'tab' => 'Einzelwerte',
                        ],
                        [
                            'name' => 'username_variable',
                            'label' => 'Benutzername Variable',
                            'placeholder' => 'username',
                            'default' => 'username',
                            'tab' => 'Einzelwerte',
                        ],
                        [
                            'name' => 'password_source',
                            'label' => 'Passwort Quelle',
                            'placeholder' => 'generated_password',
                            'tab' => 'Einzelwerte',
                        ],
                        [
                            'name' => 'password_variable',
                            'label' => 'Passwort Variable',
                            'placeholder' => 'password',
                            'default' => 'password',
                            'help' => 'Wird intern gespeichert, aber in oeffentlichen Vorschau-/Run-Ausgaben ausgeblendet.',
                            'tab' => 'Einzelwerte',
                        ],
                        [
                            'name' => 'provider_source',
                            'label' => 'Provider Quelle',
                            'placeholder' => 'literal:proton',
                            'tab' => 'Einzelwerte',
                        ],
                        [
                            'name' => 'provider_variable',
                            'label' => 'Provider Variable',
                            'placeholder' => 'provider',
                            'default' => 'provider',
                            'tab' => 'Einzelwerte',
                        ],
                        [
                            'name' => 'webmail_url_source',
                            'label' => 'Webmail-URL Quelle',
                            'placeholder' => 'account.webmailUrl',
                            'tab' => 'Weitere Werte',
                        ],
                        [
                            'name' => 'webmail_url_variable',
                            'label' => 'Webmail-URL Variable',
                            'placeholder' => 'webmail_url',
                            'default' => 'webmail_url',
                            'tab' => 'Weitere Werte',
                        ],
                        [
                            'name' => 'recovery_email_source',
                            'label' => 'Recovery-E-Mail Quelle',
                            'placeholder' => 'account.recoveryEmail',
                            'tab' => 'Weitere Werte',
                        ],
                        [
                            'name' => 'recovery_email_variable',
                            'label' => 'Recovery-E-Mail Variable',
                            'placeholder' => 'recovery_email',
                            'default' => 'recovery_email',
                            'tab' => 'Weitere Werte',
                        ],
                    ],
                ],
            ],
            'data.persist_webmail_session' => [
                'label' => 'Webmail-Session speichern',
                'kind' => 'data',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/data/persist_webmail_session.cjs',
                'php_handler' => 'App\\Services\\Workflows\\Tasks\\PersistWebmailSessionTask@handle',
                'timeout_seconds' => 30,
                'description' => 'Speichert Cookies/Storage aus dem aktuell offenen Webmailportal verschluesselt an Person oder Haupt-Verifikationskonto.',
                'form' => [
                    'selector' => false,
                    'value' => false,
                    'url' => false,
                    'mailbox_source' => true,
                    'mailbox_source_label' => 'Script-Bezugsperson',
                    'mailbox_source_options' => [
                        'person' => 'Bezugs-Person',
                        'verification' => 'Haupt-Verifikationskonto',
                    ],
                    'success_payload' => false,
                    'failure_payload' => true,
                ],
            ],
            'data.persist_browser_session' => [
                'label' => 'Browser-Session speichern',
                'kind' => 'data',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/data/persist_browser_session.cjs',
                'php_handler' => 'App\\Services\\Workflows\\Tasks\\PersistBrowserSessionTask@handle',
                'browser_window' => 'main',
                'timeout_seconds' => 30,
                'description' => 'Speichert Cookies und Browser-Storage der aktuellen Website verschluesselt an der Person. Domain und Cookie-Domains werden mitgespeichert.',
                'form' => [
                    'browser_window' => true,
                    'selector' => false,
                    'value' => false,
                    'url' => false,
                    'mailbox_source' => false,
                    'success_payload' => false,
                    'failure_payload' => true,
                    'extra_fields' => [
                        [
                            'name' => 'target_domain',
                            'label' => 'Domain/URL',
                            'placeholder' => 'leer = aktuelle Browserfenster-URL',
                            'help' => 'Optional. Beispiel: example.com oder https://example.com. Leer nutzt die URL des ausgewaehlten Browserfensters.',
                            'tab' => 'Session',
                        ],
                        [
                            'name' => 'session_key',
                            'label' => 'Session-Key',
                            'placeholder' => 'leer = Domain',
                            'help' => 'Optionaler Speichername unter metadata.browser_sessions.',
                            'tab' => 'Session',
                        ],
                        [
                            'name' => 'session_label',
                            'label' => 'Anzeigename',
                            'placeholder' => 'Shop Login, Dashboard, Webmail',
                            'tab' => 'Session',
                        ],
                    ],
                ],
            ],
            'data.delete_browser_session' => [
                'label' => 'Browser-Session/Cookies loeschen',
                'kind' => 'data',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/data/delete_browser_session.cjs',
                'php_handler' => 'App\\Services\\Workflows\\Tasks\\PersistBrowserSessionTask@delete',
                'browser_window' => 'main',
                'timeout_seconds' => 30,
                'description' => 'Loescht Cookies und Browser-Storage fuer eine Website. Ohne Domain-Eingabe wird die aktuelle URL des Browserfensters verwendet.',
                'form' => [
                    'browser_window' => true,
                    'selector' => false,
                    'value' => false,
                    'url' => false,
                    'mailbox_source' => false,
                    'success_payload' => false,
                    'failure_payload' => true,
                    'extra_fields' => [
                        [
                            'name' => 'target_domain',
                            'label' => 'Domain/URL',
                            'placeholder' => 'leer = aktuelle Browserfenster-URL',
                            'help' => 'Optional. Beispiel: example.com oder https://example.com.',
                            'tab' => 'Loeschen',
                        ],
                        [
                            'name' => 'session_key',
                            'label' => 'Session-Key',
                            'placeholder' => 'leer = Domain',
                            'help' => 'Optional. Wird genutzt, um gespeicherte Sessions gezielt aus metadata.browser_sessions zu entfernen.',
                            'tab' => 'Loeschen',
                        ],
                        [
                            'name' => 'clear_cookies',
                            'label' => 'Cookies loeschen',
                            'placeholder' => 'true',
                            'default' => 'true',
                            'help' => 'true/false',
                            'tab' => 'Loeschen',
                        ],
                        [
                            'name' => 'clear_storage',
                            'label' => 'Local/Session Storage loeschen',
                            'placeholder' => 'true',
                            'default' => 'true',
                            'help' => 'true/false',
                            'tab' => 'Loeschen',
                        ],
                    ],
                ],
            ],
            'data.workflow_return' => [
                'label' => 'Workflow-Rueckgabewert setzen',
                'kind' => 'data',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/data/workflow_return.cjs',
                'timeout_seconds' => 15,
                'description' => 'Setzt einen Rueckgabewert fuer eingebettete Workflows, damit der uebergeordnete Workflow auf true, false oder eine Variable reagieren kann.',
                'form' => [
                    'selector' => true,
                    'selector_required' => false,
                    'selector_label' => 'Variablenname',
                    'selector_placeholder' => 'workflow_return, mailbox_ready, code_found',
                    'value' => true,
                    'value_required' => false,
                    'value_label' => 'Rueckgabewert',
                    'value_placeholder' => 'true, false, Text oder JSON',
                    'url' => false,
                    'mailbox_source' => false,
                    'success_payload' => false,
                    'failure_payload' => false,
                ],
            ],
            'browser.close' => [
                'label' => 'Browserfenster schliessen',
                'kind' => 'browser',
                'runner' => 'node',
                'node_script' => 'node/workflows/tasks/browser/close.cjs',
                'timeout_seconds' => 30,
                'description' => 'Schliesst Seite, Kontext oder Browser, wenn der Runner einen Handle uebergibt.',
                'form' => [
                    'selector' => false,
                    'value' => false,
                    'url' => false,
                    'success_payload' => false,
                    'failure_payload' => false,
                ],
            ],
        ];
    }

    public function options(): array
    {
        return collect($this->all())
            ->map(fn (array $task, string $key): array => [
                'key' => $key,
                'label' => $task['label'],
                'kind' => $task['kind'],
                'runner' => $task['runner'],
                'description' => $task['description'] ?? '',
                'form' => $task['form'] ?? [],
            ])
            ->values()
            ->toArray();
    }

    public function task(string $taskKey): ?array
    {
        $definition = $this->all()[$taskKey] ?? null;

        if (! $definition) {
            return null;
        }

        return ['task_key' => $taskKey, ...$definition];
    }

    public function cardFromDefinition(string $taskKey, array $overrides = []): array
    {
        $definition = $this->task($taskKey) ?? [
            'task_key' => $taskKey,
            'label' => Str::of($taskKey)->replace(['.', '_'], ' ')->title()->toString(),
            'kind' => 'data',
            'runner' => 'php',
            'timeout_seconds' => 60,
            'description' => '',
        ];

        $card = [
            'key' => (string) ($overrides['key'] ?? Str::slug($definition['label']) ?: Str::slug($taskKey)),
            'task_key' => $definition['task_key'],
            'title' => (string) ($overrides['title'] ?? $definition['label']),
            'description' => (string) ($overrides['description'] ?? $definition['description'] ?? ''),
            'kind' => (string) ($overrides['kind'] ?? $definition['kind'] ?? 'data'),
            'runner' => (string) ($overrides['runner'] ?? $definition['runner'] ?? 'php'),
            'status' => (string) ($overrides['status'] ?? 'configured'),
            'timeout_seconds' => max(0, (int) ($overrides['timeout_seconds'] ?? $definition['timeout_seconds'] ?? 60)),
        ];

        $usesBrowserWindow = in_array((string) ($definition['kind'] ?? ''), ['browser', 'input', 'wait'], true)
            && (string) ($definition['task_key'] ?? $taskKey) !== 'wait.seconds';

        if ($usesBrowserWindow && ! array_key_exists('browser_window', $definition)) {
            $definition['browser_window'] = 'main';
        }

        foreach (['node_script', 'php_handler', 'workflow_id', 'workflow_slug', 'browser_window', 'browser_window_name', 'selector', 'element_selector', 'input_selector', 'input', 'value', 'url', 'mailbox_source', 'script_person_source', 'success_payload', 'failure_payload', 'next', 'on_partial', 'on_error', 'status_routes'] as $key) {
            $value = Arr::get($overrides, $key, Arr::get($definition, $key));

            if ($value !== null && $value !== '') {
                $card[$key] = $value;
            }
        }

        foreach (is_array(data_get($definition, 'form.extra_fields')) ? data_get($definition, 'form.extra_fields') : [] as $field) {
            if (! is_array($field)) {
                continue;
            }

            $key = preg_replace('/[^A-Za-z0-9_.-]+/', '', (string) ($field['name'] ?? '')) ?: '';

            if ($key === '') {
                continue;
            }

            $value = Arr::get($overrides, $key, Arr::get($definition, $key, $field['default'] ?? null));

            if ($value !== null && $value !== '') {
                $card[$key] = $value;
            }
        }

        return $card;
    }
}
